### ISSUE TITLE
Text Editor Recommendations inside Lesson

### ISSUE THREAD

**Issue by emcaulay** [LibraryCarpentry/lc-git#108]
@doingarchives recently raised the issue that the text editor configuration in this lesson is problematic. I would like feedback from the community about this topic.

@chendaniely, please note this is an issue that might benefit from broader discussion across multiple lessons.

**Comment by doingarchives** [comment]
I'll be able to work on a pull request incorporating the pedagogic technological considerations reflected in an Apple support document shared with @emcaulay. LC lessons are 'for beginners' so the technological component is usually less of a concern. The principal consideration (and this has been the same since the 1980s) is the hardware Apple / PC divide. At UC the staff are almost always 80% PC oriented, the students almost 80% Apple / Chromebook - part of that is a philosophical divide - namely, how hard to people want to make their work day / learning experience, and the remainder is a technological idea. In my LC classes most Apple users are opening terminal for the very first time - this after being users for many decades ... when the lesson veers into the nuances of 'choosing' a text editor - that conversation for the Apple contingent is often very strange to them.

**Comment by doingarchives** [comment]
I really only have 1 block of time reliable each week for pull requests - M 1500 - 1800  PDT. I'll see what I can do on this, but there is a more granular capitalisation issue needing attention.

**Comment by emcaulay** [comment]
I disagree with this change. I do not see a divide between Apple and PC in the way we teach this material. We have Windows users download and use Git for Windows, which allows them to use nano. 

I might ask for broader conversation from the LC community before we make any change to the text editor portion here. 

Text editors are interesting and there are tons of options, we just want to get learners through this experience and if we mandate nano, then what the instructor shows on their screen in live coding matches what the learners has on their screen.

**Comment by sstevens2** [comment]
Warning: I've not taught the LC git lesson, only the SWC one many times.

I don't really understand the issue listed above about apple vs pc.  We typically have mostly mac using instructors and about 50/50 learners.  With gitbash and having everyone use nano for the unix and git lessons, we don't really have any major issues with differences between the different OSs.

On recommendations, I usually talk briefly about how text editors are different from document editors like word.  Then I talk about how some have features that can be useful for coding and there are many different preferences.  I recommend they see what their lab is using and then have each of the helpers/instructors mention which text editor they use and why.  I'd recommend a callout about text editors more than putting it as a main part of the lesson.

**Comment by emcaulay** [comment]
Ooo, that's a great recommendation about using a callout -- that makes sense. I would support that.

**Comment by doingarchives** [comment]
Agreed - the 50/50 comment suggests a data driven thought process - if we could collect a sample on this point it would be beneficial. These are all 'lateral' discussions however among instructors / maintainers - we really need to be certain to poll the learning community - 'higher' level in my opinion since education is the name of the game or 'lower' if administrative - given that the dynamic is very decentralised and what works in different places is very important to consider. Good thoughts all.

**Comment by tobyhodges** [comment]
> we really need to be certain to poll the learning community

It would be interesting and potentially useful to have a good idea of the typical spread of operating systems one could expect to encounter when teaching a Library Carpentry workshop. For any given workshop, this is one of the pieces of information collected in The Carpentries pre-workshop survey. 

Regardless, I agree with others that the operating system being used by learners should not matter for the choice of text editor here. As @emcaulay and @sstevens2 have already said: the setup instructions help Windows users get access to a Bash shell in their system and, regardless of whether they are running Git Bash (with Git for Windows, as recommended in the lessons etup) or Windows Subsystem Linux, they will have `nano` installed.

Perhaps it would be a good idea to link from the Setup page of this Git lesson, to the equivalent in the LC Shell lesson? This may provide further help to self-directed learners visiting the LC Git lesson, who have not yet set up a Bash shell on their Windows system.

If you propose to add a discussion of what (if any) advice to give learners about which editor to use in the long run, and how that advice might differ from learner to learner/audience to audience, I think that would be best placed in the Instructor Notes for the lesson.

**Comment by emcaulay** [comment]
I made an initial small edit to Episode 2 of this lesson to include a callout box about text editors. I will submit it as a pull request as soon as the previous pull request that I submitted is reviewed and decided upon.
