### ISSUE TITLE
Optional Challenge 1: 404'd

### ISSUE THREAD

**Issue by jas58** [LibraryCarpentry/lc-git#128]
In [lesson 5: GH Pages](https://librarycarpentry.org/lc-git/05-github-pages/index.html) the first optional challenge links to thinkful.com for directions on committing to another's page.  The link 404'd for me today.
I tried searching for the title on thinkful.com, which sent me to a [repo in GitHub](https://github.com/Thinkful/guide-github-pull-request) which looped me back to the same 404 screen.
I do not know how to suggest a better link; this is an important part of the lesson for me at this stage in my learning.

**Comment by ostephens** [comment]
I think that GitHub repo contains the full text of the original Thinkful tutorial? Is this the right information: https://github.com/Thinkful/guide-github-pull-request/blob/master/index.md#time-to-submit-your-first-pr

**Comment by jas58** [comment]
Perhaps?   Thank you for parsing that repo. It was a step too far for me,
Git-novice.

The remainder of this email is my thought process.

I did not feel up to digging into someone's 8 year old repo to understand
the full structure and dig down to a single module. As I read through it,
it(self) also links to the full GitHub guide,  (
https://guides.github.com/introduction/flow/index.html), posing another
limitation: This link may also be dead as it only opened the introduction
to the full manual, which again was too much for a novice to parse. That
is,  my computer opened the home page,  not anything specific to "flow."

Is that a useful note for me when thinking about these workshops? That "all
coding is just DIY and OJT". That means the Carpentries don't actually fill
a void,  instead they do offer a paper bridge one can expect to fall
through and then sink or swim?

Or are some learners attending a workshop specially to learn what they can
ask of a research team member,  of data services? That may be specific to
my experience in the social sciences in DataCarpentry.

**Comment by tobyhodges** [comment]
Indeed, the link pointing to an outdated GitHub Guides URL\* indicates that the Thinkful repository is no longer a great resource for the lesson to use. I would suggest a fix there, but the repository has been archived and no longer accepts pull requests.

With that in mind, I suggest that the optional exercise needs a larger redesign, or otherwise should be removed. When I have taught Git, GitHub, and contributing to someone else's repository in the past, I have taken the approach of pairing up learners and demonstrating the steps they need to take to contribute to each other's repositories. One option would be to replace this optional exercise with something similar, where the Instructor can pair learners up and give them the steps to follow to open a pull request on their partner's repository\**. 

One downside to this is that it is only designed to work in a workshop setting and would not be accessible to learners following the lesson alone. However, the nature of the exercise is such that two people are required - the submitter (learner) who opens the pull request and the maintainer who receives and can merge it - and it may not be possible for us to provide a sustainable framework that would allow self-directed learners to practice this workflow. (E.g. given that the Thinkful repository was archived with >300 open pull requests, I suspect maintaining such an example repository can be a heavy burden.)

\* @jas58 if you still want to read it, I believe the correct link to the guide on GitHub Flow is https://docs.github.com/en/get-started/quickstart/github-flow#following-github-flow. I can also recommend [the Pull Requests episode of the extended version of the Software Carpentry _Version Control with Git_ lesson in The Carpentries Incubator](https://carpentries-incubator.github.io/git-novice-branch-pr/10-pull-requests/) by @sstevens2.
\** The Carpentries Curriculum Team is working on some automated approaches to create example repositories for use in teaching, which could prove helpful for an exercise like this, but I do not expect it to be ready for another few months.

**Comment by ostephens** [comment]
I think the immediate solution would be to either:
1. remove the optional exercise
2. substitute an alternative link - but I don't know the lesson well enough to know what that might be (maybe the one I found, or maybe the one suggested by @tobyhodges)

Both straightforward fixes apart from deciding the best link in (2)

**Comment by jas58** [comment]
Thank you,  Mr Hodges,  for the link options.  Ms Stevens' tutorial on
YouTube has been very clear.  Will her version from SWC be integrated with
LC? Or would an optional link to that lesson suffice for someone who wanted
to dig deeper than LC's workshop?

**Comment by tobyhodges** [comment]
@jas58 I'm afraid I do not think either option is feasible:

@sstevens2's lesson is in The Carpentries Incubator i.e. it is maintained by her rather than Software Carpentry (her lesson is using the Software Carpentry styling, which can be misleading), and due to time constraints I do not anticipate any extra content on branches and pull requests being incorporated into the official SWC lesson any time soon. 

The LC lesson could link to Sarah's lesson but, as that project is maintained only by one person (albeit one as amazing as @sstevens2!), there is always the risk that that lesson will also become outdated or disappear. This is exactly what has happened with the Thinkful tutorial that was originally linked.

I think the safest option is to link to a guide that is maintained by someone with a strong interest in keeping it up-to-date. My preference is to link to an updated version of [GitHub's guide](https://docs.github.com/en/get-started/quickstart/contributing-to-projects), that includes a step to create a new branch after cloning. I have opened [an issue to suggest the change](https://github.com/github/docs/issues/21409) and I hope the maintainers will agree. If and when that guide is improved, I will open a pull request here to update the link in the optional exercise.

**Comment by jas58** [comment]
Thank you, Mr Hodges, for setting these in motion.
Cordially,
Jennifer AW Stubbs

**Comment by tobyhodges** [comment]
My suggested change to GitHub's guide was accepted so I have opened #131 to replace the broken Thinkful link.

**Comment by emcaulay** [comment]
Thank you all for the research and discussion here. I am sorry I did not participate earlier. 

@jas58 , your recognition of this problem is very HELPFUL! Thank you for sticking through the discussion! @ostephens , thank you for your review and @tobyhodges thank you for digging all the way in and solving the problem!
