### ISSUE TITLE
Getting Started section

### ISSUE THREAD

**Issue by jmjamison** [LibraryCarpentry/lc-git#20]
I think that commands: ls, touch need to be defined. Non-linux/unix users may not be familiar with these.

**Comment by jcoliver** [comment]
I think we can assume familiarity with the bash command line interface, even if it was because learners had the lc-shell lesson taught right before this git lesson. Teaching this version control lesson to novices with no command line familiarity could be quite challenging. Not impossible, but git is foreign enough on its own without the cognitive load of seeing the CLI for the first time...

**Comment by jmjamison** [comment]
I'm not sure that is a given.  People can take Git before taking a shell class.  Even if they they do take a shell class often these people are new to all this and may need the concepts reinforced. I've been a class "helper" and know that these questions come up.

**Comment by jcoliver** [comment]
@jmjamison Check out #27 for possible solution to `ls` section. The `touch` explanation: 

> Let’s create a new file using the `touch` command, which is a quick way to create an empty file.

Seems sufficient, but do you have additional ideas for clarification of the function?

**Comment by dcmcand** [comment]
Closed by #27
