### ISSUE TITLE
More diverse examples for lessons

### ISSUE THREAD

**Issue by dcmcand** [LibraryCarpentry/lc-git#81]
We need to gather diverse examples for lessons. Ideally this would be from all types of libraries or examples that could apply to all libraries.

**Comment by Talishask** [comment]
I'm a member of The Carpentries staff and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.
---
When I go through the "Getting Start with Git" lesson, I think the course does a really good job in covering the main topics of Git, but there seems to lack some sort of practical grounding that ties the concepts together in a real-world setting. Looking at the "Version Control with Git" lesson in the Software Carpentries, they use the example of Dracula, Wolfman, and Mummy exploring planetary bases. While this is definitely silly and not a "real-world" setting, it grounds each of the steps in concrete tasks/goals rather than using the generic "hello-world" framework. I'm not saying that the lesson needs to incorporate monsters, but perhaps framing the lesson around some sort of project or task could help illustrate the real-world uses of Git/Github and make the concepts more relatable.

Another note, and also looking at the Version Control with Git lesson, is that it might be valuable to incorporate a small piece on the message flag (-m), and how to form good messages for version updates. I think this is an important element of version control and using Git, and also something that I think is a good fit for librarians to champion.

**Comment by emcaulay** [comment]
@Talishask , Thank you for passing along the comments from a Carpentries community member, and thank you @dcmcand for opening the issue. 

I am a new maintainer for this lesson and am reviewing all open issues. I won't be able to work on this issue for a little while since we have some high priority issues to address first. I hope to come back to this issue in September or October 2021.

I agree with both @dcmcand and the community member that we can improve the lesson by making it more practical.

**Comment by doingarchives** [comment]
I worked on the Code Taskforce ... and I couldn't agree more that we should be sensitive to the social / political / cultural contexts conveyed (intent = humor? ). I've called this problem out with @emcaulay in the context of a technical revision. I'm open to helping with any re write or extended conversation about the substance of this post. Also recommend the current maintainers do a 'work break down' agile scrum on what pedagogic strategy should be ... and that will need some data and use case examples from learners as well as professionals. I think we should 'close' this issue now, but be mindful that smaller related issues will be framed and worked on with a view to completing at least 1 agile story point every 20 days ... (or so).
